# 项目相关配置
ruoyi:
  # 名称
  name: 祀界
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置F:/sijie/uploadPath，Linux配置 /home/sijie/uploadPath）
  profile: /home/sijie/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
 
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey: 
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: true

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# 支付宝配置
alipay:
  appId: 2021003194643092
  serverUrl: https://openapi.alipay.com/gateway.do
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUuN1wS2kAKzIqTKFt6TepzCqi9gc3KJczy/y6MkOnm5asWPXY6B8DSds1gR/f6LJRehx9M8gCosjB2uZNvhHlqfvZcBIHmhuDKCFMNyU/yMjOrRK5aPHWDdKHX9+3t4O+FORQzzw4zGVSd8nm2kWOkYqmE6bykHtqezyiwK2LuXq3o/6nmHo68kXNlCjZD/XTPspi7wfWa2C0q1fVkgpAU5zQvkpt7LttWDoEWwPRJCWj0aPM7Lwt8ShrsioIOwtxGRX+LjcbJxhb6Wcf1Gsfn6L5XV+jOeitHeHpV9+NXMBmCn9JZCBWqyAqvnmk18HrwyLExK43VQi76K/+UNlzAgMBAAECggEAM23GLZn2QnetjlEXldGLTS1sJRRdJGbl+qR0zdKp8KDuNsVApvSGHPYCVvtDEYP/fgtzJJyucrLmJ5tR/tpWiAwDKosFwRk6oF1VPmzndaoyPr489l7jGjmHbwbpbzeH2EiTN5qiYaXU9/KyoCEk4otT3eB33/O0qfrZ2hI1MVa4ZzQyudRajwEgdqykBARFy73BQo9GmX4VOMVeLxOll97j92VMIcEOADo7XUHtm22j90/x2a21ES976/MDD4iD+xRlY0Yo9IqMmSnI9PRlVZuwhL0e500AiLdmItZYiFJy9GVtfiFBN+sSvVSSIAxRFZ0TCNebMLIhVhXNwieS0QKBgQDQo9wze9BoyymtUz0YlLBqTdbJNf/bphZB7ylHOTKwxMJ5jpTAgy4i30kMdSsXqpW9IeIZjqoakkrU3nGmIXRg3yYxL4QcLRdl0rV/mVhaspHqhmrm9QoUmvs3khROn75TsEbuqbg7ESNM1uVM2uhqpLpfDxFea4gpl91z3WZqSwKBgQC2eyd1tKGIg7OueSzpG6AgRBY+mWz/EGnrVNjReQeEGLAlnbaBlHmru3R+887kTqSOHL9lFXP5jzfLWgaRIlgm+hfZTOm+dBIaE+yGIndiZo7jYUuw2bMrEGhrZa7z1tivnh4AZAsDypInYyxl+SK8aS4aABxi3xzbnTD59RhUeQKBgCIhfCdL7OcHvTSmdkssH8P0IdveopFrFR8KIcWN/NXgCjRad8kabJS11DxeeoMvm7lJ7rPhm8AnCGjUTuEvfdtPBe9r53+4fKhilOBf1I1ZwvcLsDdCBLkkNU587ieCiF8maiQmzYWUIyMx0GcHNJglhHuCeoPosWikeEy4/kULAoGAaJZpZWMj+hRSFbvJ68kzm4qqnTJecEo+Cu1UX6rYjfOAce7UvawVmEIWYPToLZ6NXg5H/G2xTOWy+tAcV26xy5UnuhoFFm18OooU1ERI3JMfbl9DfJcpw5Lh5jwfbA5Fn1Imq96rGX8vCXgj6EZEjGxUSf6qRljON2j+uySozzECgYEAy+EtpMhnPHJil26mvbEkEa2KnvZzYjUfsNUDx37VNxv+A/KUqo6/6Ov1a/r52JluS9ZCCgK4EuSO0ThCNaBTp1bn/vO6LKklDhyPCjLiqkcZewi6I+Fg5uKOW6IY8/yHMxlaY6Q1HrF/Qgd8l0rRZwMYKYj5HjDu1kug64lWdhI=
  format: json
  charset: UTF-8
  signType: RSA2
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAngKTwsfOncot8/5n7nHY36idyE8DpBaNQ2b5+SzFmRj7zuB3x3gSL+OcBsas/yaxZnPRvmb/lPSEz0421OTMw6ys6UrhTPaV8MGXcTOcqqj7WtOqOwjtSrRoMDeDBe04f/3DzmmiOtJKT8qiMIBFB3DvJ7wB+ZzwpaAOsxXDEKIvQ/ih6y0YGl/gWpVMFnYALdYr6MOeIn+QbrbuVXhCmxl8WE/wrCx1FnSn++b7+KoL20dDl+cUte4QsREC7m0Jh9a9Gzg/zv6yPeYc0CmRjIThz45ftpYsYgFst2bN1CJRquYoXQ8A9YfkftaaautszL/FvgHCM+zyK+LktCposwIDAQAB

# 微信配置 Windows配置F:/sijie/cert/apiclient_key.pem Linux配置 /sijie/cert/apiclient_key.pem
wxpay:
  appId: wx8aa2b3d4b7ca60bb
  merchantId: 1644020957
  privateKeyPath: /sijie/cert/apiclient_key.pem
  merchantSerialNumber: 519A57EA98918E7C2B5E26B5C85F1EC3F1A08CD9
  apiV3key: 91320115MA20W8146Blovexuke040817